[project]
name = "noycomicdownloader"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "swanlab>=0.7.6",
    "textual>=6.2.1",
]
